# Generated by Django 4.1.7 on 2023-02-24 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('starting_point', models.CharField(max_length=50)),
                ('final_point', models.CharField(max_length=50)),
                ('checkpoints', models.CharField(max_length=50)),
            ],
        ),
    ]
