# Generated by Django 4.1.7 on 2023-03-07 17:13

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_fare_route_vehicle_delete_publicroutes_route_vehicle_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='route',
            name='stops',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=50), default=['a', 'b', 'c', 'd'], size=None),
            preserve_default=False,
        ),
    ]
