# Generated by Django 4.1.7 on 2023-03-08 05:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_fare_vehicle'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fare',
            name='vehicle',
        ),
    ]
