# Generated by Django 4.1.7 on 2023-02-25 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_user_vehicle_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExplorePlaces',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('location', models.CharField(max_length=50)),
                ('picture', models.ImageField(upload_to='./images')),
                ('description', models.CharField(max_length=250)),
            ],
        ),
    ]
