# Generated by Django 4.1.7 on 2023-02-27 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_remove_user_vehicle_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='email',
            field=models.EmailField(default=34344, max_length=20),
            preserve_default=False,
        ),
    ]
